# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bassirou/delivery/tek2/OOP/arcade/G-OOP-400-STG-4-1-arcade-5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bassirou/delivery/tek2/OOP/arcade/G-OOP-400-STG-4-1-arcade-5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bassirou/delivery/tek2/OOP/arcade/G-OOP-400-STG-4-1-arcade-5/CMakeFiles /home/bassirou/delivery/tek2/OOP/arcade/G-OOP-400-STG-4-1-arcade-5//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bassirou/delivery/tek2/OOP/arcade/G-OOP-400-STG-4-1-arcade-5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arcade

# Build rule for target.
arcade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade
.PHONY : arcade

# fast build rule for target.
arcade/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/build
.PHONY : arcade/fast

#=============================================================================
# Target rules for targets named libarcade

# Build rule for target.
libarcade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libarcade
.PHONY : libarcade

# fast build rule for target.
libarcade/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libarcade.dir/build.make CMakeFiles/libarcade.dir/build
.PHONY : libarcade/fast

#=============================================================================
# Target rules for targets named arcade_ncurses

# Build rule for target.
arcade_ncurses: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade_ncurses
.PHONY : arcade_ncurses

# fast build rule for target.
arcade_ncurses/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_ncurses.dir/build.make CMakeFiles/arcade_ncurses.dir/build
.PHONY : arcade_ncurses/fast

#=============================================================================
# Target rules for targets named arcade_sdl2

# Build rule for target.
arcade_sdl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade_sdl2
.PHONY : arcade_sdl2

# fast build rule for target.
arcade_sdl2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sdl2.dir/build.make CMakeFiles/arcade_sdl2.dir/build
.PHONY : arcade_sdl2/fast

#=============================================================================
# Target rules for targets named arcade_sfml

# Build rule for target.
arcade_sfml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade_sfml
.PHONY : arcade_sfml

# fast build rule for target.
arcade_sfml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sfml.dir/build.make CMakeFiles/arcade_sfml.dir/build
.PHONY : arcade_sfml/fast

#=============================================================================
# Target rules for targets named arcade_snake

# Build rule for target.
arcade_snake: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade_snake
.PHONY : arcade_snake

# fast build rule for target.
arcade_snake/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_snake.dir/build.make CMakeFiles/arcade_snake.dir/build
.PHONY : arcade_snake/fast

#=============================================================================
# Target rules for targets named arcade_pacman

# Build rule for target.
arcade_pacman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade_pacman
.PHONY : arcade_pacman

# fast build rule for target.
arcade_pacman/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_pacman.dir/build.make CMakeFiles/arcade_pacman.dir/build
.PHONY : arcade_pacman/fast

src/core/core.o: src/core/core.cpp.o
.PHONY : src/core/core.o

# target to build an object file
src/core/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/core.cpp.o
.PHONY : src/core/core.cpp.o

src/core/core.i: src/core/core.cpp.i
.PHONY : src/core/core.i

# target to preprocess a source file
src/core/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/core.cpp.i
.PHONY : src/core/core.cpp.i

src/core/core.s: src/core/core.cpp.s
.PHONY : src/core/core.s

# target to generate assembly for a file
src/core/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/core.cpp.s
.PHONY : src/core/core.cpp.s

src/core/game_loop.o: src/core/game_loop.cpp.o
.PHONY : src/core/game_loop.o

# target to build an object file
src/core/game_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/game_loop.cpp.o
.PHONY : src/core/game_loop.cpp.o

src/core/game_loop.i: src/core/game_loop.cpp.i
.PHONY : src/core/game_loop.i

# target to preprocess a source file
src/core/game_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/game_loop.cpp.i
.PHONY : src/core/game_loop.cpp.i

src/core/game_loop.s: src/core/game_loop.cpp.s
.PHONY : src/core/game_loop.s

# target to generate assembly for a file
src/core/game_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/game_loop.cpp.s
.PHONY : src/core/game_loop.cpp.s

src/core/load_libraries.o: src/core/load_libraries.cpp.o
.PHONY : src/core/load_libraries.o

# target to build an object file
src/core/load_libraries.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/load_libraries.cpp.o
.PHONY : src/core/load_libraries.cpp.o

src/core/load_libraries.i: src/core/load_libraries.cpp.i
.PHONY : src/core/load_libraries.i

# target to preprocess a source file
src/core/load_libraries.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/load_libraries.cpp.i
.PHONY : src/core/load_libraries.cpp.i

src/core/load_libraries.s: src/core/load_libraries.cpp.s
.PHONY : src/core/load_libraries.s

# target to generate assembly for a file
src/core/load_libraries.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/load_libraries.cpp.s
.PHONY : src/core/load_libraries.cpp.s

src/core/overlays/debugOverlay.o: src/core/overlays/debugOverlay.cpp.o
.PHONY : src/core/overlays/debugOverlay.o

# target to build an object file
src/core/overlays/debugOverlay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/overlays/debugOverlay.cpp.o
.PHONY : src/core/overlays/debugOverlay.cpp.o

src/core/overlays/debugOverlay.i: src/core/overlays/debugOverlay.cpp.i
.PHONY : src/core/overlays/debugOverlay.i

# target to preprocess a source file
src/core/overlays/debugOverlay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/overlays/debugOverlay.cpp.i
.PHONY : src/core/overlays/debugOverlay.cpp.i

src/core/overlays/debugOverlay.s: src/core/overlays/debugOverlay.cpp.s
.PHONY : src/core/overlays/debugOverlay.s

# target to generate assembly for a file
src/core/overlays/debugOverlay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/core/overlays/debugOverlay.cpp.s
.PHONY : src/core/overlays/debugOverlay.cpp.s

src/game/pacman/pacman.o: src/game/pacman/pacman.cpp.o
.PHONY : src/game/pacman/pacman.o

# target to build an object file
src/game/pacman/pacman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_pacman.dir/build.make CMakeFiles/arcade_pacman.dir/src/game/pacman/pacman.cpp.o
.PHONY : src/game/pacman/pacman.cpp.o

src/game/pacman/pacman.i: src/game/pacman/pacman.cpp.i
.PHONY : src/game/pacman/pacman.i

# target to preprocess a source file
src/game/pacman/pacman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_pacman.dir/build.make CMakeFiles/arcade_pacman.dir/src/game/pacman/pacman.cpp.i
.PHONY : src/game/pacman/pacman.cpp.i

src/game/pacman/pacman.s: src/game/pacman/pacman.cpp.s
.PHONY : src/game/pacman/pacman.s

# target to generate assembly for a file
src/game/pacman/pacman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_pacman.dir/build.make CMakeFiles/arcade_pacman.dir/src/game/pacman/pacman.cpp.s
.PHONY : src/game/pacman/pacman.cpp.s

src/game/snake/Snake.o: src/game/snake/Snake.cpp.o
.PHONY : src/game/snake/Snake.o

# target to build an object file
src/game/snake/Snake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_snake.dir/build.make CMakeFiles/arcade_snake.dir/src/game/snake/Snake.cpp.o
.PHONY : src/game/snake/Snake.cpp.o

src/game/snake/Snake.i: src/game/snake/Snake.cpp.i
.PHONY : src/game/snake/Snake.i

# target to preprocess a source file
src/game/snake/Snake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_snake.dir/build.make CMakeFiles/arcade_snake.dir/src/game/snake/Snake.cpp.i
.PHONY : src/game/snake/Snake.cpp.i

src/game/snake/Snake.s: src/game/snake/Snake.cpp.s
.PHONY : src/game/snake/Snake.s

# target to generate assembly for a file
src/game/snake/Snake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_snake.dir/build.make CMakeFiles/arcade_snake.dir/src/game/snake/Snake.cpp.s
.PHONY : src/game/snake/Snake.cpp.s

src/graphics/SDL2/SDL2.o: src/graphics/SDL2/SDL2.cpp.o
.PHONY : src/graphics/SDL2/SDL2.o

# target to build an object file
src/graphics/SDL2/SDL2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sdl2.dir/build.make CMakeFiles/arcade_sdl2.dir/src/graphics/SDL2/SDL2.cpp.o
.PHONY : src/graphics/SDL2/SDL2.cpp.o

src/graphics/SDL2/SDL2.i: src/graphics/SDL2/SDL2.cpp.i
.PHONY : src/graphics/SDL2/SDL2.i

# target to preprocess a source file
src/graphics/SDL2/SDL2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sdl2.dir/build.make CMakeFiles/arcade_sdl2.dir/src/graphics/SDL2/SDL2.cpp.i
.PHONY : src/graphics/SDL2/SDL2.cpp.i

src/graphics/SDL2/SDL2.s: src/graphics/SDL2/SDL2.cpp.s
.PHONY : src/graphics/SDL2/SDL2.s

# target to generate assembly for a file
src/graphics/SDL2/SDL2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sdl2.dir/build.make CMakeFiles/arcade_sdl2.dir/src/graphics/SDL2/SDL2.cpp.s
.PHONY : src/graphics/SDL2/SDL2.cpp.s

src/graphics/SDL2/SDL2KeySwitch.o: src/graphics/SDL2/SDL2KeySwitch.cpp.o
.PHONY : src/graphics/SDL2/SDL2KeySwitch.o

# target to build an object file
src/graphics/SDL2/SDL2KeySwitch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sdl2.dir/build.make CMakeFiles/arcade_sdl2.dir/src/graphics/SDL2/SDL2KeySwitch.cpp.o
.PHONY : src/graphics/SDL2/SDL2KeySwitch.cpp.o

src/graphics/SDL2/SDL2KeySwitch.i: src/graphics/SDL2/SDL2KeySwitch.cpp.i
.PHONY : src/graphics/SDL2/SDL2KeySwitch.i

# target to preprocess a source file
src/graphics/SDL2/SDL2KeySwitch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sdl2.dir/build.make CMakeFiles/arcade_sdl2.dir/src/graphics/SDL2/SDL2KeySwitch.cpp.i
.PHONY : src/graphics/SDL2/SDL2KeySwitch.cpp.i

src/graphics/SDL2/SDL2KeySwitch.s: src/graphics/SDL2/SDL2KeySwitch.cpp.s
.PHONY : src/graphics/SDL2/SDL2KeySwitch.s

# target to generate assembly for a file
src/graphics/SDL2/SDL2KeySwitch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sdl2.dir/build.make CMakeFiles/arcade_sdl2.dir/src/graphics/SDL2/SDL2KeySwitch.cpp.s
.PHONY : src/graphics/SDL2/SDL2KeySwitch.cpp.s

src/graphics/SFML/SfmlGraphic.o: src/graphics/SFML/SfmlGraphic.cpp.o
.PHONY : src/graphics/SFML/SfmlGraphic.o

# target to build an object file
src/graphics/SFML/SfmlGraphic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sfml.dir/build.make CMakeFiles/arcade_sfml.dir/src/graphics/SFML/SfmlGraphic.cpp.o
.PHONY : src/graphics/SFML/SfmlGraphic.cpp.o

src/graphics/SFML/SfmlGraphic.i: src/graphics/SFML/SfmlGraphic.cpp.i
.PHONY : src/graphics/SFML/SfmlGraphic.i

# target to preprocess a source file
src/graphics/SFML/SfmlGraphic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sfml.dir/build.make CMakeFiles/arcade_sfml.dir/src/graphics/SFML/SfmlGraphic.cpp.i
.PHONY : src/graphics/SFML/SfmlGraphic.cpp.i

src/graphics/SFML/SfmlGraphic.s: src/graphics/SFML/SfmlGraphic.cpp.s
.PHONY : src/graphics/SFML/SfmlGraphic.s

# target to generate assembly for a file
src/graphics/SFML/SfmlGraphic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sfml.dir/build.make CMakeFiles/arcade_sfml.dir/src/graphics/SFML/SfmlGraphic.cpp.s
.PHONY : src/graphics/SFML/SfmlGraphic.cpp.s

src/graphics/SFML/SfmlKeySwitch.o: src/graphics/SFML/SfmlKeySwitch.cpp.o
.PHONY : src/graphics/SFML/SfmlKeySwitch.o

# target to build an object file
src/graphics/SFML/SfmlKeySwitch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sfml.dir/build.make CMakeFiles/arcade_sfml.dir/src/graphics/SFML/SfmlKeySwitch.cpp.o
.PHONY : src/graphics/SFML/SfmlKeySwitch.cpp.o

src/graphics/SFML/SfmlKeySwitch.i: src/graphics/SFML/SfmlKeySwitch.cpp.i
.PHONY : src/graphics/SFML/SfmlKeySwitch.i

# target to preprocess a source file
src/graphics/SFML/SfmlKeySwitch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sfml.dir/build.make CMakeFiles/arcade_sfml.dir/src/graphics/SFML/SfmlKeySwitch.cpp.i
.PHONY : src/graphics/SFML/SfmlKeySwitch.cpp.i

src/graphics/SFML/SfmlKeySwitch.s: src/graphics/SFML/SfmlKeySwitch.cpp.s
.PHONY : src/graphics/SFML/SfmlKeySwitch.s

# target to generate assembly for a file
src/graphics/SFML/SfmlKeySwitch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_sfml.dir/build.make CMakeFiles/arcade_sfml.dir/src/graphics/SFML/SfmlKeySwitch.cpp.s
.PHONY : src/graphics/SFML/SfmlKeySwitch.cpp.s

src/graphics/ncurses/Ncurses.o: src/graphics/ncurses/Ncurses.cpp.o
.PHONY : src/graphics/ncurses/Ncurses.o

# target to build an object file
src/graphics/ncurses/Ncurses.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_ncurses.dir/build.make CMakeFiles/arcade_ncurses.dir/src/graphics/ncurses/Ncurses.cpp.o
.PHONY : src/graphics/ncurses/Ncurses.cpp.o

src/graphics/ncurses/Ncurses.i: src/graphics/ncurses/Ncurses.cpp.i
.PHONY : src/graphics/ncurses/Ncurses.i

# target to preprocess a source file
src/graphics/ncurses/Ncurses.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_ncurses.dir/build.make CMakeFiles/arcade_ncurses.dir/src/graphics/ncurses/Ncurses.cpp.i
.PHONY : src/graphics/ncurses/Ncurses.cpp.i

src/graphics/ncurses/Ncurses.s: src/graphics/ncurses/Ncurses.cpp.s
.PHONY : src/graphics/ncurses/Ncurses.s

# target to generate assembly for a file
src/graphics/ncurses/Ncurses.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_ncurses.dir/build.make CMakeFiles/arcade_ncurses.dir/src/graphics/ncurses/Ncurses.cpp.s
.PHONY : src/graphics/ncurses/Ncurses.cpp.s

src/graphics/ncurses/NcursesKeySwitch.o: src/graphics/ncurses/NcursesKeySwitch.cpp.o
.PHONY : src/graphics/ncurses/NcursesKeySwitch.o

# target to build an object file
src/graphics/ncurses/NcursesKeySwitch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_ncurses.dir/build.make CMakeFiles/arcade_ncurses.dir/src/graphics/ncurses/NcursesKeySwitch.cpp.o
.PHONY : src/graphics/ncurses/NcursesKeySwitch.cpp.o

src/graphics/ncurses/NcursesKeySwitch.i: src/graphics/ncurses/NcursesKeySwitch.cpp.i
.PHONY : src/graphics/ncurses/NcursesKeySwitch.i

# target to preprocess a source file
src/graphics/ncurses/NcursesKeySwitch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_ncurses.dir/build.make CMakeFiles/arcade_ncurses.dir/src/graphics/ncurses/NcursesKeySwitch.cpp.i
.PHONY : src/graphics/ncurses/NcursesKeySwitch.cpp.i

src/graphics/ncurses/NcursesKeySwitch.s: src/graphics/ncurses/NcursesKeySwitch.cpp.s
.PHONY : src/graphics/ncurses/NcursesKeySwitch.s

# target to generate assembly for a file
src/graphics/ncurses/NcursesKeySwitch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade_ncurses.dir/build.make CMakeFiles/arcade_ncurses.dir/src/graphics/ncurses/NcursesKeySwitch.cpp.s
.PHONY : src/graphics/ncurses/NcursesKeySwitch.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menu/SelectMenu.o: src/menu/SelectMenu.cpp.o
.PHONY : src/menu/SelectMenu.o

# target to build an object file
src/menu/SelectMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/menu/SelectMenu.cpp.o
.PHONY : src/menu/SelectMenu.cpp.o

src/menu/SelectMenu.i: src/menu/SelectMenu.cpp.i
.PHONY : src/menu/SelectMenu.i

# target to preprocess a source file
src/menu/SelectMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/menu/SelectMenu.cpp.i
.PHONY : src/menu/SelectMenu.cpp.i

src/menu/SelectMenu.s: src/menu/SelectMenu.cpp.s
.PHONY : src/menu/SelectMenu.s

# target to generate assembly for a file
src/menu/SelectMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/menu/SelectMenu.cpp.s
.PHONY : src/menu/SelectMenu.cpp.s

src/menu/UserInputMenu.o: src/menu/UserInputMenu.cpp.o
.PHONY : src/menu/UserInputMenu.o

# target to build an object file
src/menu/UserInputMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/menu/UserInputMenu.cpp.o
.PHONY : src/menu/UserInputMenu.cpp.o

src/menu/UserInputMenu.i: src/menu/UserInputMenu.cpp.i
.PHONY : src/menu/UserInputMenu.i

# target to preprocess a source file
src/menu/UserInputMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/menu/UserInputMenu.cpp.i
.PHONY : src/menu/UserInputMenu.cpp.i

src/menu/UserInputMenu.s: src/menu/UserInputMenu.cpp.s
.PHONY : src/menu/UserInputMenu.s

# target to generate assembly for a file
src/menu/UserInputMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/menu/UserInputMenu.cpp.s
.PHONY : src/menu/UserInputMenu.cpp.s

src/menu/UsernameSelection.o: src/menu/UsernameSelection.cpp.o
.PHONY : src/menu/UsernameSelection.o

# target to build an object file
src/menu/UsernameSelection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/menu/UsernameSelection.cpp.o
.PHONY : src/menu/UsernameSelection.cpp.o

src/menu/UsernameSelection.i: src/menu/UsernameSelection.cpp.i
.PHONY : src/menu/UsernameSelection.i

# target to preprocess a source file
src/menu/UsernameSelection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/menu/UsernameSelection.cpp.i
.PHONY : src/menu/UsernameSelection.cpp.i

src/menu/UsernameSelection.s: src/menu/UsernameSelection.cpp.s
.PHONY : src/menu/UsernameSelection.s

# target to generate assembly for a file
src/menu/UsernameSelection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/menu/UsernameSelection.cpp.s
.PHONY : src/menu/UsernameSelection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... libarcade"
	@echo "... arcade"
	@echo "... arcade_ncurses"
	@echo "... arcade_pacman"
	@echo "... arcade_sdl2"
	@echo "... arcade_sfml"
	@echo "... arcade_snake"
	@echo "... src/core/core.o"
	@echo "... src/core/core.i"
	@echo "... src/core/core.s"
	@echo "... src/core/game_loop.o"
	@echo "... src/core/game_loop.i"
	@echo "... src/core/game_loop.s"
	@echo "... src/core/load_libraries.o"
	@echo "... src/core/load_libraries.i"
	@echo "... src/core/load_libraries.s"
	@echo "... src/core/overlays/debugOverlay.o"
	@echo "... src/core/overlays/debugOverlay.i"
	@echo "... src/core/overlays/debugOverlay.s"
	@echo "... src/game/pacman/pacman.o"
	@echo "... src/game/pacman/pacman.i"
	@echo "... src/game/pacman/pacman.s"
	@echo "... src/game/snake/Snake.o"
	@echo "... src/game/snake/Snake.i"
	@echo "... src/game/snake/Snake.s"
	@echo "... src/graphics/SDL2/SDL2.o"
	@echo "... src/graphics/SDL2/SDL2.i"
	@echo "... src/graphics/SDL2/SDL2.s"
	@echo "... src/graphics/SDL2/SDL2KeySwitch.o"
	@echo "... src/graphics/SDL2/SDL2KeySwitch.i"
	@echo "... src/graphics/SDL2/SDL2KeySwitch.s"
	@echo "... src/graphics/SFML/SfmlGraphic.o"
	@echo "... src/graphics/SFML/SfmlGraphic.i"
	@echo "... src/graphics/SFML/SfmlGraphic.s"
	@echo "... src/graphics/SFML/SfmlKeySwitch.o"
	@echo "... src/graphics/SFML/SfmlKeySwitch.i"
	@echo "... src/graphics/SFML/SfmlKeySwitch.s"
	@echo "... src/graphics/ncurses/Ncurses.o"
	@echo "... src/graphics/ncurses/Ncurses.i"
	@echo "... src/graphics/ncurses/Ncurses.s"
	@echo "... src/graphics/ncurses/NcursesKeySwitch.o"
	@echo "... src/graphics/ncurses/NcursesKeySwitch.i"
	@echo "... src/graphics/ncurses/NcursesKeySwitch.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu/SelectMenu.o"
	@echo "... src/menu/SelectMenu.i"
	@echo "... src/menu/SelectMenu.s"
	@echo "... src/menu/UserInputMenu.o"
	@echo "... src/menu/UserInputMenu.i"
	@echo "... src/menu/UserInputMenu.s"
	@echo "... src/menu/UsernameSelection.o"
	@echo "... src/menu/UsernameSelection.i"
	@echo "... src/menu/UsernameSelection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

